version: "3.8"

services:
    mysql_server:
        image: mysql:8.0
        container_name: bookstoreDB
        environment:
            - MYSQL_DATABASE=bookstore
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - "3306:3306"
